apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: barnacle-e2e
  labels:
    app.kubernetes.io/name: registry
    app.kubernetes.io/part-of: barnacle-e2e
spec:
  selector:
    app.kubernetes.io/name: registry
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30500
      name: registry
  type: NodePort
