apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: barnacle-e2e
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: barnacle-e2e
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP
