// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Barnacle Support",
            "url": "https://github.com/pdylanross/barnacle/issues"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/nodes": {
            "get": {
                "description": "Returns a list of all registered nodes in the cluster",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "List nodes",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nodesapi.ListNodesResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/me": {
            "get": {
                "description": "Returns information about this node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Get current node",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nodesapi.NodeResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}": {
            "get": {
                "description": "Returns information about a specific node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "nodes"
                ],
                "summary": "Get node",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/nodesapi.NodeResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}/blobs": {
            "get": {
                "description": "Returns all blobs cached on the specified node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "List blobs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/blobsapi.ListBlobsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}/blobs/finalize": {
            "post": {
                "description": "Completes a blob transfer by updating Redis location",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rebalance"
                ],
                "summary": "Finalize blob transfer",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Finalize request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rebalanceapi.FinalizeRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rebalanceapi.FinalizeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}/blobs/receive": {
            "post": {
                "description": "Receives blob data for a reserved transfer",
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rebalance"
                ],
                "summary": "Receive blob data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Reservation ID",
                        "name": "X-Reservation-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Expected blob digest",
                        "name": "X-Digest",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rebalanceapi.ReceiveResponse"
                        }
                    },
                    "400": {
                        "description": "Digest mismatch",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    },
                    "404": {
                        "description": "Reservation not found or expired",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}/blobs/reserve": {
            "post": {
                "description": "Reserves disk space for an incoming blob transfer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "rebalance"
                ],
                "summary": "Reserve space for blob",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reserve request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rebalanceapi.ReserveRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rebalanceapi.ReserveResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    },
                    "409": {
                        "description": "Blob already exists",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    },
                    "507": {
                        "description": "Insufficient storage",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/nodes/{nodeId}/blobs/{digest}": {
            "get": {
                "description": "Returns information about a specific blob on the node",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Get blob",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Blob digest",
                        "name": "digest",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/blobsapi.BlobResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a specific blob from the node's cache",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "blobs"
                ],
                "summary": "Delete blob",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Node identifier",
                        "name": "nodeId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Blob digest",
                        "name": "digest",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/api/v1/upstreams": {
            "get": {
                "description": "Returns a list of all configured upstream registry aliases",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upstreams"
                ],
                "summary": "List upstreams",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/upstreamsapi.ListUpstreamsResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/upstreams/{alias}": {
            "get": {
                "description": "Returns details for a specific upstream registry",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "upstreams"
                ],
                "summary": "Get upstream",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Upstream alias",
                        "name": "alias",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/upstreamsapi.GetUpstreamResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/httptk.ErrorsList"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns the health status of the service",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Health status",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "blobsapi.BlobResponse": {
            "type": "object",
            "properties": {
                "accessCount5m": {
                    "description": "AccessCount5m is the number of accesses in the last 5 minutes.",
                    "type": "integer",
                    "example": 42
                },
                "digest": {
                    "description": "Digest is the content-addressable digest of the blob (e.g., \"sha256:abc123...\").",
                    "type": "string",
                    "example": "sha256:abc123def456..."
                },
                "diskPath": {
                    "description": "DiskPath is the filesystem path where the blob is stored.",
                    "type": "string",
                    "example": "/var/cache/barnacle/hot/sha256/ab/abc123def456"
                },
                "mediaType": {
                    "description": "MediaType is the OCI media type of the blob.",
                    "type": "string",
                    "example": "application/vnd.oci.image.layer.v1.tar+gzip"
                },
                "size": {
                    "description": "Size is the size of the blob in bytes.",
                    "type": "integer",
                    "example": 1048576
                },
                "tier": {
                    "description": "Tier is the cache tier number where this blob resides.",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "blobsapi.ListBlobsResponse": {
            "type": "object",
            "properties": {
                "blobs": {
                    "description": "Blobs is a list of all cached blobs on this node.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/blobsapi.BlobResponse"
                    }
                }
            }
        },
        "httptk.ErrorsList": {
            "type": "object",
            "properties": {
                "errors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/httptk.HTTPErrorDTO"
                    }
                }
            }
        },
        "httptk.HTTPErrorDTO": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "BLOB_UNKNOWN"
                },
                "detail": {},
                "message": {
                    "type": "string",
                    "example": "blob unknown to registry"
                }
            }
        },
        "nodesapi.DiskUsageResponse": {
            "type": "object",
            "properties": {
                "freeBytes": {
                    "description": "FreeBytes is the available space in bytes.",
                    "type": "integer",
                    "example": 53687091200
                },
                "path": {
                    "description": "Path is the filesystem path for this cache tier.",
                    "type": "string",
                    "example": "/var/cache/barnacle/hot"
                },
                "totalBytes": {
                    "description": "TotalBytes is the total size of the filesystem in bytes.",
                    "type": "integer",
                    "example": 107374182400
                },
                "usedBytes": {
                    "description": "UsedBytes is the used space in bytes.",
                    "type": "integer",
                    "example": 53687091200
                }
            }
        },
        "nodesapi.ListNodesResponse": {
            "type": "object",
            "properties": {
                "nodes": {
                    "description": "Nodes is a list of all registered nodes.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodesapi.NodeResponse"
                    }
                }
            }
        },
        "nodesapi.NodeResponse": {
            "type": "object",
            "properties": {
                "lastUpdated": {
                    "description": "LastUpdated is the timestamp when this information was last updated.",
                    "type": "string"
                },
                "nodeId": {
                    "description": "NodeID is the unique identifier for this node.",
                    "type": "string",
                    "example": "node-1"
                },
                "stats": {
                    "description": "Stats contains high-level statistics about the node.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/nodesapi.StatsResponse"
                        }
                    ]
                },
                "status": {
                    "description": "Status indicates the current operational state of the node.",
                    "type": "string",
                    "example": "ready"
                }
            }
        },
        "nodesapi.StatsResponse": {
            "type": "object",
            "properties": {
                "tierDiskUsage": {
                    "description": "TierDiskUsage contains disk usage statistics for each cache tier.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/nodesapi.DiskUsageResponse"
                    }
                }
            }
        },
        "rebalanceapi.FinalizeRequest": {
            "type": "object",
            "required": [
                "digest",
                "reservationId"
            ],
            "properties": {
                "digest": {
                    "description": "Digest is the digest of the blob being finalized.",
                    "type": "string",
                    "example": "sha256:abc123def456..."
                },
                "reservationId": {
                    "description": "ReservationID is the reservation to finalize.",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                },
                "tier": {
                    "description": "Tier is the cache tier where the blob was stored.",
                    "type": "integer",
                    "example": 0
                }
            }
        },
        "rebalanceapi.FinalizeResponse": {
            "type": "object",
            "properties": {
                "success": {
                    "description": "Success indicates whether finalization succeeded.",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "rebalanceapi.ReceiveResponse": {
            "type": "object",
            "properties": {
                "digest": {
                    "description": "Digest is the digest of the received blob.",
                    "type": "string",
                    "example": "sha256:abc123def456..."
                },
                "size": {
                    "description": "Size is the size of the received blob in bytes.",
                    "type": "integer",
                    "example": 1048576
                }
            }
        },
        "rebalanceapi.ReserveRequest": {
            "type": "object",
            "required": [
                "digest",
                "mediaType",
                "size",
                "sourceNodeId"
            ],
            "properties": {
                "digest": {
                    "description": "Digest is the content-addressable digest of the blob to reserve space for.",
                    "type": "string",
                    "example": "sha256:abc123def456..."
                },
                "mediaType": {
                    "description": "MediaType is the OCI media type of the blob.",
                    "type": "string",
                    "example": "application/vnd.oci.image.layer.v1.tar+gzip"
                },
                "size": {
                    "description": "Size is the size of the blob in bytes.",
                    "type": "integer",
                    "minimum": 1,
                    "example": 1048576
                },
                "sourceNodeId": {
                    "description": "SourceNodeID is the node that currently holds the blob.",
                    "type": "string",
                    "example": "node-1"
                }
            }
        },
        "rebalanceapi.ReserveResponse": {
            "type": "object",
            "properties": {
                "expiresAt": {
                    "description": "ExpiresAt is when this reservation expires if not used.",
                    "type": "string",
                    "example": "2024-01-15T10:30:00Z"
                },
                "reservationId": {
                    "description": "ReservationID is a unique identifier for this reservation.",
                    "type": "string",
                    "example": "550e8400-e29b-41d4-a716-446655440000"
                }
            }
        },
        "upstreamsapi.GetUpstreamResponse": {
            "type": "object",
            "properties": {
                "alias": {
                    "description": "Alias is the unique name for this upstream registry.",
                    "type": "string",
                    "example": "dockerhub"
                },
                "authType": {
                    "description": "AuthType is the type of authentication configured for this upstream.\nPossible values: \"anonymous\", \"basic\", \"bearer\".",
                    "type": "string",
                    "example": "anonymous"
                },
                "registry": {
                    "description": "Registry is the URL or hostname of the upstream registry.",
                    "type": "string",
                    "example": "registry-1.docker.io"
                }
            }
        },
        "upstreamsapi.ListUpstreamsResponse": {
            "type": "object",
            "properties": {
                "upstreams": {
                    "description": "Upstreams is a list of configured upstream registry aliases.",
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "dockerhub",
                        "ghcr"
                    ]
                }
            }
        }
    },
    "tags": [
        {
            "description": "Health and system status",
            "name": "system"
        },
        {
            "description": "Node lifecycle and health management",
            "name": "nodes"
        },
        {
            "description": "Upstream container registry configuration",
            "name": "upstreams"
        },
        {
            "description": "Blob cache inspection and management",
            "name": "blobs"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Barnacle API",
	Description:      "Pull-through caching proxy for OCI container registries.\n\nBarnacle provides a distributed caching layer in front of upstream\ncontainer registries, with multi-node coordination via Redis.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
